### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Glowman554** [Glowman554/phoenix-v2#1]
- Stack
- [x] sp reg (16 bit)
- [x] push
- [x] pop
- [x] lsp (load stack ptr)
- [x] rsp (read stack ptr)
-------------------------------
- more registers
- [x] r6-r15
-------------------------------
- [x] jof / jno (jump overflow / jump no overflow)
- [x] cfg (clear flags)
- [x] ado (add if overflow)
- [x] sbo (sub if overflow)
-------------------------------
- interrupts
- [x] inth reg (16 bit)
- [x] lih (load interrupt handler)
- [x] wfg / rfg instructions (read / write flag register into register) 
-------------------------------
- [x] increase controll lines to 64 from 32
-------------------------------
- timer (8 bit)
- [x] prescaler io reg
- [x] compare io reg
- [x] ctl io reg
- [x] interrupt connection
- [x] add pulse out / toggle out and interrupt modes
